import Sarah from "../../../../../static/images/admin-sarah.png";
import Cert from "../../../../../static/images/image-Cert.png";
import Kristy from "../../../../../static/images/Kristy.svg";
import { FcGoogle } from "react-icons/fc";

const talentUsers = [
  {
    id: 24,
    subPlan: "Silver Plan",
    userPics: Sarah,
    userName: "Sarah Hue",
    userType: "Employer",
    userDate: "2nd April 2022",
    detailLink: "View details",
    subGroup: "New account",
    category: "employer",
    cert: Cert,
  },
  {
    id: 25,
    subPlan: "Silver Plan",
    userPics: Sarah,
    userName: "Sarah Hue",
    userType: "Employer",
    userDate: "2nd April 2022",
    detailLink: "View details",
    subGroup: "New account",
    category: "employer",
    cert: Cert,
  },
  {
    id: 26,
    subPlan: "Silver Plan",
    userPics: Sarah,
    userName: "Sarah Hue",
    userType: "Employer",
    userDate: "2nd April 2022",
    detailLink: "View details",
    subGroup: "New account",
    category: "employer",
    cert: Cert,
  },
  {
    id: 27,
    subPlan: "Silver Plan",
    userPics: Sarah,
    userName: "Sarah Hue",
    userType: "Employer",
    userDate: "2nd April 2022",
    detailLink: "View details",
    subGroup: "New account",
    category: "employer",
    cert: Cert,
  },
];
const recuritter = [
  {
    id: 1,
    companyLogo: <FcGoogle />,
    companyName: "Google Plc",
    userType: "Tech Employer",
    companyDetails: "See full details",
  },
  {
    id: 2,
    companyLogo: <FcGoogle />,
    companyName: "Google Plc",
    userType: "Tech Employer",
    companyDetails: "See full details",
  },
  {
    id: 3,
    companyLogo: <FcGoogle />,
    companyName: "Google Plc",
    userType: "Tech Employer",
    companyDetails: "See full details",
  },
  {
    id: 4,
    companyLogo: <FcGoogle />,
    companyName: "Google Plc",
    userType: "Tech Employer",
    companyDetails: "See full details",
  },
  {
    id: 5,
    companyLogo: <FcGoogle />,
    companyName: "Google Plc",
    userType: "Tech Employer",
    companyDetails: "See full details",
  },
  {
    id: 6,
    companyLogo: <FcGoogle />,
    companyName: "Google Plc",
    userType: "Tech Employer",
    companyDetails: "See full details",
  },
  {
    id: 7,
    companyLogo: <FcGoogle />,
    companyName: "Google Plc",
    userType: "Tech Employer",
    companyDetails: "See full details",
  },
  {
    id: 8,
    companyLogo: <FcGoogle />,
    companyName: "Google Plc",
    userType: "Tech Employer",
    companyDetails: "See full details",
  },
  {
    id: 9,
    companyLogo: <FcGoogle />,
    companyName: "Google Plc",
    userType: "Tech Employer",
    companyDetails: "See full details",
  },
  {
    id: 10,
    companyLogo: <FcGoogle />,
    companyName: "Google Plc",
    userType: "Tech Employer",
    companyDetails: "See full details",
  },
];
export { talentUsers, recuritter };
