import Activate from "../../../../../static/icons/restric-icon.svg";
import Sarah from "../../../../../static/images/admin-sarah.png";
import Cert from "../../../../../static/images/image-Cert.png";
import Kristy from "../../../../../static/images/Kristy.svg";
import { FcGoogle } from "react-icons/fc";

const talentUsers = [
  {
    id: 1,
    subPlan: "Silver Plan",
    userPics: Sarah,
    restricIcon: Activate,
    userName: "Sarah Hue",
    userType: "Talent",
    userDate: "22nd February 2020",
    detailLink: "View details",
    subGroup: "Reactivate",
    category: "talent",
    cert: Cert,
  },
  {
    id: 2,
    subPlan: "Silver Plan",
    userPics: Sarah,
    restricIcon: Activate,
    userName: "Sarah Hue",
    userType: "Talent",
    userDate: "2nd April 2022",
    detailLink: "View details",
    subGroup: "Suspend",
    category: "talent",
    cert: Cert,
  },
  {
    id: 3,
    subPlan: "Silver Plan",
    userPics: Sarah,
    restricIcon: Activate,
    userName: "Sarah Hue",
    userType: "Talent",
    userDate: "22nd February 2020",
    detailLink: "View details",
    subGroup: "Suspend",
    category: "talent",
    cert: Cert,
  },
  {
    id: 4,
    subPlan: "Silver Plan",
    userPics: Sarah,
    restricIcon: Activate,
    userName: "Sarah Hue",
    userType: "Talent",
    userDate: "23rd January 2023",
    detailLink: "View details",
    subGroup: "New account",
    category: "talent",
    cert: Cert,
  },
  {
    id: 5,
    subPlan: "Silver Plan",
    userPics: Sarah,
    restricIcon: Activate,
    userName: "Sarah Hue",
    userType: "Talent",
    userDate: "22nd February 2020",
    detailLink: "View details",
    subGroup: "New account",
    category: "talent",
    cert: Cert,
  },
  {
    id: 6,
    subPlan: "Silver Plan",
    userPics: Sarah,
    restricIcon: Activate,
    userName: "Sarah Hue",
    userType: "Talent",
    userDate: "2nd April 2022",
    detailLink: "View details",
    subGroup: "Suspend",
    category: "talent",
    cert: Cert,
  },
  {
    id: 7,
    subPlan: "Silver Plan",
    userPics: Sarah,
    restricIcon: Activate,
    userName: "Sarah Hue",
    userType: "Talent",
    userDate: "23rd January 2023",
    detailLink: "View details",
    subGroup: "Reactivate",
    category: "talent",
    cert: Cert,
  },
  {
    id: 8,
    subPlan: "Silver Plan",
    userPics: Sarah,
    restricIcon: Activate,
    userName: "Sarah Hue",
    userType: "Talent",
    userDate: "2nd April 2022",
    detailLink: "View details",
    subGroup: "Suspend",
    category: "talent",
    cert: Cert,
  },
  {
    id: 9,
    subPlan: "Silver Plan",
    userPics: Sarah,
    restricIcon: Activate,
    userName: "Sarah Hue",
    userType: "Talent",
    userDate: "22nd February 2020",
    detailLink: "View details",
    subGroup: "Reactivate",
    category: "talent",
    cert: Cert,
  },
  {
    id: 10,
    subPlan: "Silver Plan",
    userPics: Sarah,
    restricIcon: Activate,
    userName: "Sarah Hue",
    userType: "Talent",
    userDate: "2nd April 2022",
    detailLink: "View details",
    subGroup: "New account",
    category: "talent",
    cert: Cert,
  },
  {
    id: 11,
    subPlan: "Silver Plan",
    userPics: Sarah,
    restricIcon: Activate,
    userName: "Sarah Hue",
    userType: "Agent",
    userDate: "23rd January 2023",
    detailLink: "View details",
    subGroup: "Reactivate",
    category: "agent",
    cert: Cert,
  },
  {
    id: 12,
    subPlan: "Silver Plan",
    userPics: Sarah,
    restricIcon: Activate,
    userName: "Sarah Hue",
    userType: "Agent",
    userDate: "2nd April 2022",
    detailLink: "View details",
    subGroup: "suspend",
    category: "agent",
    cert: Cert,
  },
  {
    id: 13,
    subPlan: "Silver Plan",
    userPics: Sarah,
    restricIcon: Activate,
    userName: "Sarah Hue",
    userType: "Agent",
    userDate: "2nd April 2022",
    detailLink: "View details",
    subGroup: "suspend",
    category: "agent",
    cert: Cert,
  },
  {
    id: 14,
    subPlan: "Silver Plan",
    userPics: Sarah,
    restricIcon: Activate,
    userName: "Sarah Hue",
    userType: "Agent",
    userDate: "2nd April 2022",
    detailLink: "View details",
    subGroup: "Reactivate",
    category: "agent",
    cert: Cert,
  },
  {
    id: 15,
    subPlan: "Silver Plan",
    userPics: Sarah,
    restricIcon: Activate,
    userName: "Sarah Hue",
    userType: "Agent",
    userDate: "2nd April 2022",
    detailLink: "View details",
    subGroup: "Reactivate",
    category: "agent",
    cert: Cert,
  },
  {
    id: 16,
    subPlan: "Silver Plan",
    userPics: Sarah,
    restricIcon: Activate,
    userName: "Sarah Hue",
    userType: "Agent",
    userDate: "2nd April 2022",
    detailLink: "View details",
    subGroup: "New account",
    category: "agent",
    cert: Cert,
  },
  {
    id: 17,
    subPlan: "Silver Plan",
    userPics: Sarah,
    restricIcon: Activate,
    userName: "Sarah Hue",
    userType: "Agent",
    userDate: "2nd April 2022",
    detailLink: "View details",
    subGroup: "New account",
    category: "agent",
    cert: Cert,
  },
  {
    id: 18,
    subPlan: "Silver Plan",
    userPics: Sarah,
    restricIcon: Activate,
    userName: "Sarah Hue",
    userType: "Agent",
    userDate: "2nd April 2022",
    detailLink: "View details",
    subGroup: "suspend",
    category: "agent",
    cert: Cert,
  },
  {
    id: 19,
    subPlan: "Silver Plan",
    userPics: Sarah,
    restricIcon: Activate,
    userName: "Sarah Hue",
    userType: "Agent",
    userDate: "2nd April 2022",
    detailLink: "View details",
    subGroup: "suspend",
    category: "agent",
    cert: Cert,
  },
  {
    id: 20,
    subPlan: "Silver Plan",
    userPics: Sarah,
    restricIcon: Activate,
    userName: "Sarah Hue",
    userType: "Agent",
    userDate: "2nd April 2022",
    detailLink: "View details",
    subGroup: "Reactivate",
    category: "agent",
    cert: Cert,
  },
  {
    id: 21,
    subPlan: "Silver Plan",
    userPics: Sarah,
    restricIcon: Activate,
    userName: "Sarah Hue",
    userType: "Employer",
    userDate: "2nd April 2022",
    detailLink: "View details",
    subGroup: "Suspend",
    category: "employer",
    cert: Cert,
  },
  {
    id: 22,
    subPlan: "Silver Plan",
    userPics: Sarah,
    restricIcon: Activate,
    userName: "Sarah Hue",
    userType: "Employer",
    userDate: "2nd April 2022",
    detailLink: "View details",
    subGroup: "Reactivate",
    category: "employer",
    cert: Cert,
  },
  {
    id: 23,
    subPlan: "Silver Plan",
    userPics: Sarah,
    restricIcon: Activate,
    userName: "Sarah Hue",
    userType: "Employer",
    userDate: "2nd April 2022",
    detailLink: "View details",
    subGroup: "Reactivate",
    category: "employer",
    cert: Cert,
  },
  {
    id: 24,
    subPlan: "Silver Plan",
    userPics: Sarah,
    restricIcon: Activate,
    userName: "Sarah Hue",
    userType: "Employer",
    userDate: "2nd April 2022",
    detailLink: "View details",
    subGroup: "New account",
    category: "employer",
    cert: Cert,
  },
  {
    id: 25,
    subPlan: "Silver Plan",
    userPics: Sarah,
    restricIcon: Activate,
    userName: "Sarah Hue",
    userType: "Employer",
    userDate: "2nd April 2022",
    detailLink: "View details",
    subGroup: "New account",
    category: "employer",
    cert: Cert,
  },
  {
    id: 26,
    subPlan: "Silver Plan",
    userPics: Sarah,
    restricIcon: Activate,
    userName: "Sarah Hue",
    userType: "Employer",
    userDate: "2nd April 2022",
    detailLink: "View details",
    subGroup: "New account",
    category: "employer",
    cert: Cert,
  },
  {
    id: 27,
    subPlan: "Silver Plan",
    userPics: Sarah,
    restricIcon: Activate,
    userName: "Sarah Hue",
    userType: "Employer",
    userDate: "2nd April 2022",
    detailLink: "View details",
    subGroup: "New account",
    category: "employer",
    cert: Cert,
  },
];
const employerUsers = [
  {
    id: 1,
    subPlan: "Silver Plan",
    userPics: Sarah,
    restricIcon: Activate,
    userName: "Sarah Hue",
    userType: "Employer",
    userDate: "22nd February 2020",
    detailLink: "View details",
    subGroup: "Reactivate",
  },
  {
    id: 2,
    subPlan: "Silver Plan",
    userPics: Sarah,
    restricIcon: Activate,
    userName: "Sarah Hue",
    userType: "Employer",
    userDate: "23rd January 2023",
    detailLink: "View details",
    subGroup: "Suspend",
  },
  {
    id: 3,
    subPlan: "Silver Plan",
    userPics: Sarah,
    restricIcon: Activate,
    userName: "Sarah Hue",
    userType: "Employer",
    userDate: "2nd April 2022",
    detailLink: "View details",
    subGroup: "Suspend",
  },
  {
    id: 4,
    subPlan: "Silver Plan",
    userPics: Sarah,
    restricIcon: Activate,
    userName: "Sarah Hue",
    userType: "Employer",
    userDate: "23rd January 2023",
    detailLink: "View details",
    subGroup: "Reactivate",
  },
  {
    id: 5,
    subPlan: "Silver Plan",
    userPics: Sarah,
    restricIcon: Activate,
    userName: "Sarah Hue",
    userType: "Employer",
    userDate: "22nd February 2020",
    detailLink: "View details",
    subGroup: "Suspend",
  },
  {
    id: 6,
    subPlan: "Silver Plan",
    userPics: Sarah,
    restricIcon: Activate,
    userName: "Sarah Hue",
    userType: "Employer",
    userDate: "2nd April 2022",
    detailLink: "View details",
    subGroup: "Suspend",
  },
  {
    id: 7,
    subPlan: "Silver Plan",
    userPics: Sarah,
    restricIcon: Activate,
    userName: "Sarah Hue",
    userType: "Employer",
    userDate: "23rd January 2023",
    detailLink: "View details",
    subGroup: "Reactivate",
  },
  {
    id: 8,
    subPlan: "Silver Plan",
    userPics: Sarah,
    restricIcon: Activate,
    userName: "Sarah Hue",
    userType: "Employer",
    userDate: "2nd April 2022",
    detailLink: "View details",
    subGroup: "Suspend",
  },
  {
    id: 9,
    subPlan: "Silver Plan",
    userPics: Sarah,
    restricIcon: Activate,
    userName: "Sarah Hue",
    userType: "Employer",
    userDate: "2nd April 2022",
    detailLink: "View details",
    subGroup: "Reactivate",
  },
  {
    id: 10,
    subPlan: "Silver Plan",
    userPics: Sarah,
    restricIcon: Activate,
    userName: "Sarah Hue",
    userType: "Employer",
    userDate: "22nd February 2020",
    detailLink: "View details",
    subGroup: "Suspend",
  },
  {
    id: 11,
    subPlan: "Silver Plan",
    userPics: Sarah,
    restricIcon: Activate,
    userName: "Sarah Hue",
    userType: "Employer",
    userDate: "23rd January 2023",
    detailLink: "View details",
    subGroup: "Reactivate",
  },
  {
    id: 12,
    subPlan: "Silver Plan",
    userPics: Sarah,
    restricIcon: Activate,
    userName: "Sarah Hue",
    userDate: "22nd February 2020",
    userType: "Employer",
    detailLink: "View details",
    subGroup: "Reactivate",
  },
];
const usersToVet = [
  {
    id: 1,
    userName: "Sarah Hue",
    userPics: Sarah,
    skill: "Frontend Developer",
    category: "employer",
    role: "Neo Corp, CTO",
  },
  {
    id: 2,
    userName: "John Doe",
    userPics: Sarah,
    skill: "Frontend Developer",
    category: "employer",
    role: "Neo Corp, CTO",
  },
  {
    id: 3,
    userName: "June Hue",
    userPics: Sarah,
    skill: "Frontend Developer",
    category: "employer",
    role: "Neo Corp, CTO",
  },
  {
    id: 4,
    userPics: Sarah,
    userName: "Jamal Doe",
    skill: "Frontend Developer",
    category: "employer",
    role: "Digtech Inc, HR",
  },
  {
    id: 5,
    userPics: Sarah,
    userName: "Jamal Doe",
    skill: "Frontend Developer",
    category: "agent",
    role: "Digtech Inc, HR",
  },
  {
    id: 6,
    userPics: Sarah,
    userName: "Jamal Doe",
    skill: "Frontend Developer",
    category: "agent",
    role: "Digtech Inc, HR",
  },
  {
    id: 7,
    userPics: Sarah,
    userName: "Jamal Doe",
    skill: "Frontend Developer",
    category: "agent",
    role: "Digtech Inc, HR",
  },
  {
    id: 8,
    userPics: Sarah,
    userName: "Jamal Doe",
    skill: "Frontend Developer",
    category: "agent",
    role: "Neo Corp, CTO",
  },
  {
    id: 9,
    userPics: Sarah,
    userName: "Jamal Doe",
    skill: "Frontend Developer",
    category: "talent",
    role: "Neo Corp, CTO",
  },
  {
    id: 10,
    userPics: Sarah,
    userName: "Jamal Doe",
    skill: "Frontend Developer",
    category: "talent",
    role: "Neo Corp, CTO",
  },
  {
    id: 11,
    userPics: Sarah,
    userName: "Jamal Doe",
    skill: "Frontend Developer",
    category: "talent",
    role: "Neo Corp, CTO",
  },
  {
    id: 12,
    userPics: Sarah,
    userName: "Jamal Doe",
    skill: "Frontend Developer",
    category: "talent",
    role: "Neo Corp, CTO",
  },
];
const vettedUsers = [
  {
    id: 1,
    userPics: Sarah,
    userName: "Bayo Adigun",
    skill: "Frontend Developer",
    category: "employer",
    role: "Neo Corp, CTO",
  },
  {
    id: 2,
    userPics: Sarah,
    userName: "Titus Fish",
    skill: "Frontend Developer",
    category: "employer",
    role: "Neo Corp, CTO",
  },
  {
    id: 3,
    userPics: Sarah,
    userName: "Wayne Brooks",
    skill: "Frontend Developer",
    category: "employer",
    role: "Neo Corp, CTO",
  },
  {
    id: 4,
    userPics: Sarah,
    userName: "Wayne Brooks",
    skill: "Frontend Developer",
    category: "agent",
    role: "Neo Corp, CTO",
  },
  {
    id: 5,
    userPics: Sarah,
    userName: "Wayne Brooks",
    skill: "Frontend Developer",
    category: "agent",
    role: "Neo Corp, CTO",
  },
  {
    id: 6,
    userPics: Sarah,
    userName: "Wayne Brooks",
    skill: "Frontend Developer",
    category: "agent",
    role: "Neo Corp, CTO",
  },
  {
    id: 7,
    userPics: Sarah,
    userName: "Wayne Brooks",
    skill: "Frontend Developer",
    category: "talent",
  },
  {
    id: 8,
    userPics: Sarah,
    userName: "Wayne Brooks",
    skill: "Frontend Developer",
    category: "talent",
  },
  {
    id: 9,
    userPics: Sarah,
    userName: "Wayne Brooks",
    skill: "Frontend Developer",
    category: "talent",
  },
];

const recuritter = [
  {
    id: 1,
    companyLogo: <FcGoogle />,
    companyName: "Google Plc",
    userType: "Tech Employer",
    companyDetails: "See full details",
  },
  {
    id: 2,
    companyLogo: <FcGoogle />,
    companyName: "Google Plc",
    userType: "Tech Employer",
    companyDetails: "See full details",
  },
  {
    id: 3,
    companyLogo: <FcGoogle />,
    companyName: "Google Plc",
    userType: "Tech Employer",
    companyDetails: "See full details",
  },
  {
    id: 4,
    companyLogo: <FcGoogle />,
    companyName: "Google Plc",
    userType: "Tech Employer",
    companyDetails: "See full details",
  },
  {
    id: 5,
    companyLogo: <FcGoogle />,
    companyName: "Google Plc",
    userType: "Tech Employer",
    companyDetails: "See full details",
  },
  {
    id: 6,
    companyLogo: <FcGoogle />,
    companyName: "Google Plc",
    userType: "Tech Employer",
    companyDetails: "See full details",
  },
  {
    id: 7,
    companyLogo: <FcGoogle />,
    companyName: "Google Plc",
    userType: "Tech Employer",
    companyDetails: "See full details",
  },
  {
    id: 8,
    companyLogo: <FcGoogle />,
    companyName: "Google Plc",
    userType: "Tech Employer",
    companyDetails: "See full details",
  },
  {
    id: 9,
    companyLogo: <FcGoogle />,
    companyName: "Google Plc",
    userType: "Tech Employer",
    companyDetails: "See full details",
  },
  {
    id: 10,
    companyLogo: <FcGoogle />,
    companyName: "Google Plc",
    userType: "Tech Employer",
    companyDetails: "See full details",
  },
];
const jobsToBeVetted = [
  {
    id: 1,
    employerPics: Kristy,
    employerName: "Kristy Haag",
    userType: "Employer",
    jobCategory: "Web Development",
    budget: "$ 500",
    description:
      "Repudiandae alias assumenda consectetur laborum. Ut dolorem vero quo atque. Unde est ut sed illo consequatur quam qui ut. Qui optio atque sed itaque cumque. Est est sit saepe beatae dolorum porro impedit minus. Molestias quia minima cumque eius quoic sint ut recusandae nesciunt temporibus.",
    detailLink: "See more",
  },
  {
    id: 2,
    employerPics: Kristy,
    employerName: "Kristy Haag",
    userType: "Employer",
    jobCategory: "Web Development",
    budget: "$ 500",
    description:
      "Repudiandae alias assumenda consectetur laborum. Ut dolorem vero quo atque. Unde est ut sed illo consequatur quam qui ut. Qui optio atque sed itaque cumque. Est est sit saepe beatae dolorum porro impedit minus. Molestias quia minima cumque eius quoic sint ut recusandae nesciunt temporibus.",
    detailLink: "See more",
  },
  {
    id: 3,
    employerPics: Kristy,
    employerName: "Kristy Haag",
    userType: "Employer",
    jobCategory: "Web Development",
    budget: "$ 500",
    description:
      "Repudiandae alias assumenda consectetur laborum. Ut dolorem vero quo atque. Unde est ut sed illo consequatur quam qui ut. Qui optio atque sed itaque cumque. Est est sit saepe beatae dolorum porro impedit minus. Molestias quia minima cumque eius quoic sint ut recusandae nesciunt temporibus.",
    detailLink: "See more",
  },
  {
    id: 4,
    employerPics: Kristy,
    employerName: "Kristy Haag",
    userType: "Employer",
    jobCategory: "Web Development",
    budget: "$ 500",
    description:
      "Repudiandae alias assumenda consectetur laborum. Ut dolorem vero quo atque. Unde est ut sed illo consequatur quam qui ut. Qui optio atque sed itaque cumque. Est est sit saepe beatae dolorum porro impedit minus. Molestias quia minima cumque eius quoic sint ut recusandae nesciunt temporibus.",
    detailLink: "See more",
  },
  {
    id: 5,
    employerPics: Kristy,
    employerName: "Kristy Haag",
    userType: "Employer",
    jobCategory: "Web Development",
    budget: "$ 500",
    description:
      "Repudiandae alias assumenda consectetur laborum. Ut dolorem vero quo atque. Unde est ut sed illo consequatur quam qui ut. Qui optio atque sed itaque cumque. Est est sit saepe beatae dolorum porro impedit minus. Molestias quia minima cumque eius quoic sint ut recusandae nesciunt temporibus.",
    detailLink: "See more",
  },
  {
    id: 6,
    employerPics: Kristy,
    employerName: "Kristy Haag",
    userType: "Employer",
    jobCategory: "Web Development",
    budget: "$ 500",
    description:
      "Repudiandae alias assumenda consectetur laborum. Ut dolorem vero quo atque. Unde est ut sed illo consequatur quam qui ut. Qui optio atque sed itaque cumque. Est est sit saepe beatae dolorum porro impedit minus. Molestias quia minima cumque eius quoic sint ut recusandae nesciunt temporibus.",
    detailLink: "See more",
  },
  {
    id: 7,
    employerPics: Kristy,
    employerName: "Kristy Haag",
    userType: "Employer",
    jobCategory: "Web Development",
    budget: "$ 500",
    description:
      "Repudiandae alias assumenda consectetur laborum. Ut dolorem vero quo atque. Unde est ut sed illo consequatur quam qui ut. Qui optio atque sed itaque cumque. Est est sit saepe beatae dolorum porro impedit minus. Molestias quia minima cumque eius quoic sint ut recusandae nesciunt temporibus.",
    detailLink: "See more",
  },
  {
    id: 8,
    employerPics: Kristy,
    employerName: "Kristy Haag",
    userType: "Employer",
    jobCategory: "Web Development",
    budget: "$ 500",
    description:
      "Repudiandae alias assumenda consectetur laborum. Ut dolorem vero quo atque. Unde est ut sed illo consequatur quam qui ut. Qui optio atque sed itaque cumque. Est est sit saepe beatae dolorum porro impedit minus. Molestias quia minima cumque eius quoic sint ut recusandae nesciunt temporibus.",
    detailLink: "See more",
  },
];

const jobManagementData = [
  {
    id: 1,
    employerPics: Kristy,
    category: "Employer",
    employerName: "Kristy Haag",
    userType: "Employer",
    jobCategory: "Web Development",
    budget: "$ 500",
    description:
      "Repudiandae alias assumenda consectetur laborum. Ut dolorem vero quo atque. Unde est ut sed illo consequatur quam qui ut. Qui optio atque sed itaque cumque. Est est sit saepe beatae dolorum porro impedit minus. Molestias quia minima cumque eius quoic sint ut recusandae nesciunt temporibus.",
    detailLink: "See more",
  },
  {
    id: 2,
    employerPics: Kristy,
    category: "Employer",
    employerName: "Kristy Haag",
    userType: "Employer",
    jobCategory: "Web Development",
    budget: "$ 500",
    description:
      "Repudiandae alias assumenda consectetur laborum. Ut dolorem vero quo atque. Unde est ut sed illo consequatur quam qui ut. Qui optio atque sed itaque cumque. Est est sit saepe beatae dolorum porro impedit minus. Molestias quia minima cumque eius quoic sint ut recusandae nesciunt temporibus.",
    detailLink: "See more",
  },
  {
    id: 3,
    employerPics: Kristy,
    category: "Employer",
    employerName: "Kristy Haag",
    userType: "Employer",
    jobCategory: "Web Development",
    budget: "$ 500",
    description:
      "Repudiandae alias assumenda consectetur laborum. Ut dolorem vero quo atque. Unde est ut sed illo consequatur quam qui ut. Qui optio atque sed itaque cumque. Est est sit saepe beatae dolorum porro impedit minus. Molestias quia minima cumque eius quoic sint ut recusandae nesciunt temporibus.",
    detailLink: "See more",
  },
  {
    id: 4,
    employerPics: Kristy,
    category: "Employer",
    employerName: "Kristy Haag",
    userType: "Employer",
    jobCategory: "Web Development",
    budget: "$ 500",
    description:
      "Repudiandae alias assumenda consectetur laborum. Ut dolorem vero quo atque. Unde est ut sed illo consequatur quam qui ut. Qui optio atque sed itaque cumque. Est est sit saepe beatae dolorum porro impedit minus. Molestias quia minima cumque eius quoic sint ut recusandae nesciunt temporibus.",
    detailLink: "See more",
  },
  {
    id: 5,
    employerPics: Kristy,
    category: "Employer",
    employerName: "Kristy Haag",
    userType: "Employer",
    jobCategory: "Web Development",
    budget: "$ 500",
    description:
      "Repudiandae alias assumenda consectetur laborum. Ut dolorem vero quo atque. Unde est ut sed illo consequatur quam qui ut. Qui optio atque sed itaque cumque. Est est sit saepe beatae dolorum porro impedit minus. Molestias quia minima cumque eius quoic sint ut recusandae nesciunt temporibus.",
    detailLink: "See more",
  },
  {
    id: 6,
    employerPics: Kristy,
    category: "Agent",
    employerName: "Kristy Haag",
    userType: "Employer",
    jobCategory: "Web Development",
    budget: "$ 500",
    description:
      "Repudiandae alias assumenda consectetur laborum. Ut dolorem vero quo atque. Unde est ut sed illo consequatur quam qui ut. Qui optio atque sed itaque cumque. Est est sit saepe beatae dolorum porro impedit minus. Molestias quia minima cumque eius quoic sint ut recusandae nesciunt temporibus.",
    detailLink: "See more",
  },
  {
    id: 7,
    employerPics: Kristy,
    category: "Agent",
    employerName: "Kristy Haag",
    userType: "Employer",
    jobCategory: "Web Development",
    budget: "$ 500",
    description:
      "Repudiandae alias assumenda consectetur laborum. Ut dolorem vero quo atque. Unde est ut sed illo consequatur quam qui ut. Qui optio atque sed itaque cumque. Est est sit saepe beatae dolorum porro impedit minus. Molestias quia minima cumque eius quoic sint ut recusandae nesciunt temporibus.",
    detailLink: "See more",
  },
  {
    id: 8,
    employerPics: Kristy,
    category: "Agent",
    employerName: "Kristy Haag",
    userType: "Employer",
    jobCategory: "Web Development",
    budget: "$ 500",
    description:
      "Repudiandae alias assumenda consectetur laborum. Ut dolorem vero quo atque. Unde est ut sed illo consequatur quam qui ut. Qui optio atque sed itaque cumque. Est est sit saepe beatae dolorum porro impedit minus. Molestias quia minima cumque eius quoic sint ut recusandae nesciunt temporibus.",
    detailLink: "See more",
  },
  {
    id: 9,
    employerPics: Kristy,
    category: "Agent",
    employerName: "Kristy Haag",
    userType: "Employer",
    jobCategory: "Web Development",
    budget: "$ 500",
    description:
      "Repudiandae alias assumenda consectetur laborum. Ut dolorem vero quo atque. Unde est ut sed illo consequatur quam qui ut. Qui optio atque sed itaque cumque. Est est sit saepe beatae dolorum porro impedit minus. Molestias quia minima cumque eius quoic sint ut recusandae nesciunt temporibus.",
    detailLink: "See more",
  },
  {
    id: 10,
    employerPics: Kristy,
    category: "Agent",
    employerName: "Kristy Haag",
    userType: "Employer",
    jobCategory: "Web Development",
    budget: "$ 500",
    description:
      "Repudiandae alias assumenda consectetur laborum. Ut dolorem vero quo atque. Unde est ut sed illo consequatur quam qui ut. Qui optio atque sed itaque cumque. Est est sit saepe beatae dolorum porro impedit minus. Molestias quia minima cumque eius quoic sint ut recusandae nesciunt temporibus.",
    detailLink: "See more",
  },
];
export {
  talentUsers,
  employerUsers,
  usersToVet,
  vettedUsers,
  recuritter,
  jobsToBeVetted,
  jobManagementData,
};
